### ISSUE TITLE
Steps for installation unclear (particularly on Linux)

### ISSUE THREAD

**Issue by ytzemih** [lanthale/PhotoSlide#1]
Hi, awesome idea, I'd like to install it under Linux but don't know how to do that. Could you, please, add a small guide on how to install PhotoSlide? Thx, Mario ;)

**Comment by maifeeulasad** [comment]
It is a `maven` project, so all you have to do is first have maven in your environment. Then install fresh dependencies. When done build the project and export JAR or JARs(for stand-alone). Then find which file contains Main class. Some name related to project would be the best guess. Then create a **_sh_** file, which targets that JAR file. I think that's how you have to create it's custom build.

I'm just suggesting, I haven't tried it yet.

**Comment by lanthale** [comment]
I have now created an installer for every platform.

https://github.com/lanthale/PhotoSlide/releases/tag/v0.3

Please can you test if it is working (Linux is now a DEB package) ?

**Comment by lanthale** [comment]
Now install packages for Linux are in release v0.3. For Linux I have created a DEB package, if you need an rpm let me know. 

Clemens

**Comment by ytzemih** [comment]
@lanthale, @maifeeulasad: Here is what I needed to do for Ubuntu 19.10:

1. Download and unpack ZIP file.
2. Run `sudo dpkg -i photoslide_1.0.0-1_amd64.deb`
3. Run `/opt/photoslide/bin/PhotoSlide`

No need to install `maven` or anything else. Thx @lanthale for a very nice looking app. I think this piece of information could be added to the `readme.md`.

**Comment by maifeeulasad** [comment]
@lanthale it's really cool that you've published package for ubuntu. I've checked it out, it looks great. But I encountered some issues, so I reported some bugs and enhancements. Please check those out.

@ytzemih I didn't knew about that actually. All those Java-Maven project I've worked on I followed those steps, that's the reason why I suggested those.

**Comment by lanthale** [comment]
Now I have created a new version with bug fixes for the main topics
