### ISSUE TITLE
Icon quality too low

### ISSUE THREAD

**Issue by maifeeulasad** [lanthale/PhotoSlide#3]
Please check this ss, icon quality is too low :

![rsz_screenshot_from_2020-10-14_16-52-40_copy](https://user-images.githubusercontent.com/29339330/95979810-0a63b580-0e3e-11eb-8cde-35d3d607750a.png)

**Comment by lanthale** [comment]
I have to create new icons anyway.

**Comment by lanthale** [comment]
New icons are now available. Can you try out ?
