### ISSUE TITLE
Application icon doesn't show up and title/hint says Java

### ISSUE THREAD

**Issue by maifeeulasad** [lanthale/PhotoSlide#4]
Please check out the ss:

![rsz_screenshot_from_2020-10-14_16-55-38](https://user-images.githubusercontent.com/29339330/95980073-70e8d380-0e3e-11eb-8220-7a28cd65323a.png)

**Comment by maifeeulasad** [comment]
Maybe I can work on this, if you're looking for collaborators, you can assign me in.

**Comment by lanthale** [comment]
Issue is now solved in the current version.
