### ISSUE TITLE
Text aren't completely visible

### ISSUE THREAD

**Issue by maifeeulasad** [lanthale/PhotoSlide#5]
Please check out this ss, the **Browse** isn't completely visible : 

![Screenshot from 2020-10-14 16-59-19](https://user-images.githubusercontent.com/29339330/95980295-c45b2180-0e3e-11eb-83c2-d8b763a47eb7.png)

**Comment by lanthale** [comment]
Now as well fixed.

**Comment by maifeeulasad** [comment]
@lanthale but, in [0.3.2](https://github.com/lanthale/PhotoSlide/releases/tag/v0.3.2) the bug is still present

**Comment by lanthale** [comment]
Again a fix for the issue.
