### ISSUE TITLE
[Enhancement] Add percentage along with file scanned

### ISSUE THREAD

**Issue by maifeeulasad** [lanthale/PhotoSlide#6]
Currently it just shows, which file it's loading to memory, but I think it would be really cool, if you add a percentage right beside that.

![rsz_screenshot_from_2020-10-14_17-02-43](https://user-images.githubusercontent.com/29339330/95980770-74c92580-0e3f-11eb-95c2-629b86853438.png)

And without loading all of them to memory, it would be really cool loading few at a times. Sort of pagination.

**Comment by maifeeulasad** [comment]
If you want you can assign me to this too

**Comment by lanthale** [comment]
I have implemented this. Regarding the pagination is already there from the GridView component from the ControlsFX. It is using the VirtualView class which is also used by other Javafx components. But you are right it could be improved to use less memory.

I will assign it to you.

**Comment by lanthale** [comment]
I have now updated the paganination to reduce the memory footprint of the gridview. Some small issues are left and it would help you can investigate further memory optimisations for the gridview component. Actually it consumes 2-3 GB of ram for 10.000 images in one folder.
