### ISSUE TITLE
TIFF file doesn't show up

### ISSUE THREAD

**Issue by maifeeulasad** [lanthale/PhotoSlide#7]
I was really looking forward to have some GUI on my research project and was planning to use this. As I read in doc that it supports TIFF, but none of the TIFF files got loaded.

Please check this ss : 
![Screenshot from 2020-10-14 17-07-22](https://user-images.githubusercontent.com/29339330/95981085-f456f480-0e3f-11eb-95b7-176ab9a5826a.png)

But the default _Image Viewer_ can open those files.

**Comment by lanthale** [comment]
I have now enabled TIFF support. The reason why I have hold it back is that I wanted to use the Javafx Extension mechanism to load TIFF files. Now I have enabled via SwingFXUtils.toFXImage to get the image. Th downside is that I do not get any progess during loading. But for now I think it is ok.

I will upload in an hour a new version which includes that
