### ISSUE TITLE
Module org.reactfx not found

### ISSUE THREAD

**Issue by dmolony** [lanthale/PhotoSlide#8]
New installation on OSX:

[INFO] --- moditect-maven-plugin:1.0.0.RC1:create-runtime-image (create-runtime-image) @ PhotoSlide ---
[ERROR] Error: Module org.reactfx not found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:30 min
[INFO] Finished at: 2020-10-15T09:07:00+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.moditect:moditect-maven-plugin:1.0.0.RC1:create-runtime-image (create-runtime-image) on project PhotoSlide: Execution create-runtime-image of goal org.moditect:moditect-maven-plugin:1.0.0.RC1:create-runtime-image failed: Execution of jlink failed -> [Help 1]

**Comment by lanthale** [comment]
Ok interesting because I have never tried a fresh installation. On Windows the fresh installation is working and downloads the module org.reactfx. Can you try to build a second time ? Because I had on windows the issue that only the second time the build was working ?

**Comment by dmolony** [comment]
After the fourth retry:

MBP4:~/Documents/GitLocal/PhotoSlide % mvn clean compile package -Ppackage -f PhotoSlide/pom.xml
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< org.photoslide:PhotoSlide >----------------------
[INFO] Building PhotoSlide 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ PhotoSlide ---
[INFO] Deleting /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ PhotoSlide ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 21 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ PhotoSlide ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 24 source files to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/classes
[INFO] /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/src/main/java/org/photoslide/lighttable/LighttableController.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/src/main/java/org/photoslide/lighttable/LighttableController.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ PhotoSlide ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 21 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ PhotoSlide ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 24 source files to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/classes
[INFO] /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/src/main/java/org/photoslide/lighttable/LighttableController.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/src/main/java/org/photoslide/lighttable/LighttableController.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ PhotoSlide ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ PhotoSlide ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ PhotoSlide ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-dependency-plugin:3.1.1:copy-dependencies (copy-libs) @ PhotoSlide ---
[INFO] Copying slf4j-api-2.0.0-alpha1.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/slf4j-api-2.0.0-alpha1.jar
[INFO] Copying javafx-media-15.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/javafx-media-15.jar
[INFO] Copying ikonli-javafx-11.5.0.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/ikonli-javafx-11.5.0.jar
[INFO] Copying javafx-swing-15-mac.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/javafx-swing-15-mac.jar
[INFO] Copying javafx-base-15-mac.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/javafx-base-15-mac.jar
[INFO] Copying ikonli-themify-pack-11.5.0.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/ikonli-themify-pack-11.5.0.jar
[INFO] Copying slf4j-simple-2.0.0-alpha1.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/slf4j-simple-2.0.0-alpha1.jar
[INFO] Copying icafe-1.1-SNAPSHOT.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/icafe-1.1-SNAPSHOT.jar
[INFO] Copying javafx-controls-15-mac.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/javafx-controls-15-mac.jar
[INFO] Copying javafx-graphics-15.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/javafx-graphics-15.jar
[INFO] Copying javafx-fxml-15.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/javafx-fxml-15.jar
[INFO] Copying javafx-graphics-15-mac.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/javafx-graphics-15-mac.jar
[INFO] Copying javafx-media-15-mac.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/javafx-media-15-mac.jar
[INFO] Copying ikonli-core-11.5.0.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/ikonli-core-11.5.0.jar
[INFO] Copying javafx-swing-15.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/javafx-swing-15.jar
[INFO] Copying controlsfx-11.0.2.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/controlsfx-11.0.2.jar
[INFO] Copying javafx-base-15.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/javafx-base-15.jar
[INFO] Copying ikonli-fontawesome-pack-11.5.0.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/ikonli-fontawesome-pack-11.5.0.jar
[INFO] Copying javafx-controls-15.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/javafx-controls-15.jar
[INFO] Copying jai-imageio-core-1.3.0.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/jai-imageio-core-1.3.0.jar
[INFO] Copying javafx-fxml-15-mac.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/javafx-fxml-15-mac.jar
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ PhotoSlide ---
[INFO] Building jar: /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/PhotoSlide-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- copy-rename-maven-plugin:1.0.1:copy (copy-target) @ PhotoSlide ---
[INFO] Copied /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/PhotoSlide-1.0-SNAPSHOT.jar to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/modules/PhotoSlide-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- moditect-maven-plugin:1.0.0.RC1:add-module-info (add-module-info-to-deps) @ PhotoSlide ---
writing to /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/moditect/PhotoSlide/versions/11/module-info.java
[INFO] Created module descriptor at /Users/denismolony/Documents/GitLocal/PhotoSlide/PhotoSlide/target/moditect/generated-sources/PhotoSlide/module-info.java
[INFO]
[INFO] --- moditect-maven-plugin:1.0.0.RC1:create-runtime-image (create-runtime-image) @ PhotoSlide ---
[ERROR] Error: Module org.reactfx not found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.850 s
[INFO] Finished at: 2020-10-16T04:56:53+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.moditect:moditect-maven-plugin:1.0.0.RC1:create-runtime-image (create-runtime-image) on project PhotoSlide: Execution create-runtime-image of goal org.moditect:moditect-maven-plugin:1.0.0.RC1:create-runtime-image failed: Execution of jlink failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by lanthale** [comment]
I have now found the issue. You have to set the JAVA_HOME environment var. 
On OSX: export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home
before you execute the mvn cmd.
