### ISSUE TITLE
Multipage TIF doesn't show up

### ISSUE THREAD

**Issue by maifeeulasad** [lanthale/PhotoSlide#9]
Currently it can't load multi-page TIF files.

I've added the file [here](https://drive.google.com/file/d/1xdQgrKJT8jgFXw2J0mkgT63ulZggpUZD/view?usp=sharing)

Like this :
![Screenshot from 2020-10-15 13-44-40](https://user-images.githubusercontent.com/29339330/96092784-2a05e700-0eed-11eb-9e76-9027c05272cd.png)

**Comment by lanthale** [comment]
Thank you for the test. I have now identified that the ending "tif" was not on the list but also the TIFF lib cannot read TIFF properly (black pages). I have wrote the author and hope to get soon some feedback. I will let you know when full TIFF support is implemented.

**Comment by maifeeulasad** [comment]
@lanthale do you have any plan to downgrade this project to **JDK11** ?

**Comment by lanthale** [comment]
Not yet but it should be possible because I am not using too much topics from jdk 15. 

The last release now fixes finally multi page tiff’s. The first page is only shown. Later I want to implement page switching.
